"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import navbar from "@/components/navbar/Navbar";
import Navbar from "@/components/navbar/Navbar";
import { SessionProvider } from "next-auth/react";
import { Component } from "react";

const inter = Inter({ subsets: ["latin"] });
import { usePathname } from "next/navigation";

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const LayoutProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const pathname = usePathname();
  return (
    <>
      {pathname !== "/" && <Navbar />}
      {children}
    </>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <LayoutProvider>{/* <Navbar /> */}</LayoutProvider>
          {children}
        </div>
      </body>
    </html>
  );
}
