version: '3'

services:

#  frontend:
#    build:
#      context: ${FRONTEND_PATH}
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#    networks:
#      - transcendence
#    volumes:
#      - "frontend-data:/app/data"

  backend:
    build:
      context: ./backend/pong-backend/
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    networks:
      - transcendence
#    depends_on:
#      - db
    volumes:
      - "./backend/srcs:/app/data"
#  db:
#    image: postgres:12
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    networks:
#      - transcendence

networks:
  transcendence:
    name: transcendence
