version: "3.9"

services:

   backend:
     build:
       context: ${BACKEND_PATH}
       dockerfile: Dockerfile
       target: development
     env_file:
       - backend/.env
     ports:
       - "8000:8000
     depends_on:
       - db
     volumes:
        - "./backend/volume:/app/data"

   frontend:
    build:
      context: ${FRONTEND_PATH}
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
       - "./frontend/volume:/app/data"

   db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env

   adminer:
     image: adminer
     restart: always
     ports:
       - "8080:8080"

